multi-region: conditional bootstrap
dcos-terraform/terraform-aws-infrastructure pull request #11
Opened 2018-12-28 16:01 UTC by bernadinm

This adds control to enable a bootstrap node on the remote region

2019-01-10 07:49 UTC, fatz requested changes
have to review other modules first. But keeping this as changes requested because of non registry source

2019-01-10 07:49 UTC, fatz commented on main.tf
> +  source  = "github.com/dcos-terraform/terraform-aws-vpc?ref=multi-region"
needs to be changed before merge

2019-01-10 07:49 UTC, fatz commented on main.tf
> +  source = "github.com/dcos-terraform/terraform-aws-security-groups?ref=multi-region"
needs to be changed before merge

2019-01-10 07:49 UTC, fatz commented on main.tf
> +  source = "github.com/dcos-terraform/terraform-aws-bootstrap?ref=conditional-bootstrap"
needs to be changed before merge

2019-01-10 07:49 UTC, fatz commented on .gitignore
> +# Inspired by https://dcmnt.me/2bidtTq
can we please keep the .gitignore clean. A lot of entries which are not needed for this project

2019-01-11 07:10 UTC, fatz commented
@bernadinm can you take care of the conflicts?

2019-01-11 22:12 UTC, bernadinm commented
complete, thanks @fatz !

2019-01-14 14:09 UTC, fatz commented
terraform fmt failed. @bernadinm please have a look at jenkins

2019-01-15 00:22 UTC, bernadinm commented
This is blocked by this PR here: https://github.com/dcos-terraform/terraform-aws-bootstrap/pull/6

2019-01-15 23:41 UTC, bernadinm commented
conflicts are taken care of, merging

2019-01-15 23:41 UTC, merged