Fix source argument in README example
dcos-terraform/terraform-aws-infrastructure pull request #15
Opened 2019-01-21 09:56 UTC by mrnugget

This updates the `source` in the README, which used the `masters` module, not the `infrastructure` one contained in this repository. It also changes the name of the defined module to reflect that.

I would also propose to add this to the example, so it's ready to go:

```hcl
output "bootstrap-public-ip" {
  value = "${module.dcos-infrastructure.bootstrap.public_ip}"
}

output "masters-public-ips" {
  value = "${module.dcos-infrastructure.masters.public_ips}"
}
```

But I just wanted to commit the fix first before I possibly add a second commit. Let me know what you think!

2019-01-21 10:17 UTC, fatz commented
@mrnugget thanks a lot. We probably copy+pasted that example from the masters module and forgot to change the ref. 

About adding the output: I don't see anything against adding it so please feel free.

To pass the CI build can you please run a README build after adding your second commit.

```
$ docker run -ti -v$(pwd):/a --entrypoint /usr/bin/terraform-docs fatz/terraform-jenkins md /a > README.md
```

Sorry just saw you edited the `README.md` itself please take a look into the header section of `main.tf` We use a genereator to create the README

2019-01-21 10:22 UTC, fatz requested changes
see my comment.

2019-01-21 10:24 UTC, mrnugget commented
@fatz Ah! I didn't see that the README was auto-generated. I amended my first commit, auto-generated the README and then did the same for the second commit.

2019-01-22 09:56 UTC, mrnugget commented
Hmmm, is the Jenkins job failing _because_ I changed something in the README? Looks like it checks whether there's a diff: https://jenkins-terraform.mesosphere.com/service/dcos-terraform-jenkins/job/dcos-terraform/job/terraform-aws-infrastructure/job/PR-15/2/console

2019-01-22 10:12 UTC, fatz commented
you have to change the header of `main.tf` see here https://github.com/dcos-terraform/terraform-aws-infrastructure/blob/master/main.tf#L1-L37

2019-01-22 12:27 UTC, mrnugget commented
But that's what I did:

- https://github.com/dcos-terraform/terraform-aws-infrastructure/pull/15/commits/4b415eb30eda392c5fd07ec943474bfc030446fd
- https://github.com/dcos-terraform/terraform-aws-infrastructure/pull/15/commits/bd3f59635219d9e09a7c27b631b988c1abef80f6

Both of these modify `README` and `main.tf` — should I change them to _only_ modify the `main.tf` file?

2019-01-22 12:53 UTC, fatz commented
and you ran the command I stated here https://github.com/dcos-terraform/terraform-aws-infrastructure/pull/15#issuecomment-456020678

2019-01-23 08:44 UTC, mrnugget commented
Yep, exactly like that. Running it again produces no changes:

```
$ git status
On branch patch-1
Your branch is up to date with 'origin/patch-1'.

nothing to commit, working tree clean

$ docker run -ti -v$(pwd):/a --entrypoint /usr/bin/terraform-docs fatz/terraform-jenkins md /a > README.md

$ git status
On branch patch-1
Your branch is up to date with 'origin/patch-1'.

nothing to commit, working tree clean

```

2019-01-25 15:09 UTC, fatz approved these changes

2019-01-25 15:09 UTC, merged